server:
  port: 80
mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.161.255:3307/LOL?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 200

  #邮件服务配置
  mail:
    host: smtp.qq.com
    username: 532132647@qq.com
    password: kzvtfjozariabijc
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
        starttls:
          enable: true
          required: true
    default-encoding: UTF-8
    fromMail:
      addr: 532132647@qq.com

  #redis相关配置
  redis:
    host: 47.98.161.255
    password: password
    port: 6380
    database: 0
    timeout: 10000
    jedis:
      pool:
        max-active: 50
        max-wait: -1
        max-idle: 20
        min-idle: 2

#跨域配置，开发环境
cors-config: "*"

#请求python接口的地址和端口
python-address: 47.98.161.255
python-port: 9999

